### ISSUE TITLE
Movie is parsed as TV show

### ISSUE THREAD

**Issue by flowan** [pr0pz/scene-release-parser-php#12] opened 2024-05-28 19:36 UTC
Hi,

The movie release `V.H.S.94.2021.BluRay.1080p.DTS-HD.MA.5.1.AVC-GROUPNAME` is parsed as a TV show. This is probably because `REGEX_SEASON` sees `S.94` as a season.

Im not sure how to fix this.

**Comment by flowan** [comment] 2024-05-28 19:43
Btw, when a release contains `HULU` it is always marked as tv show

**Comment by pr0pz** [comment] 2024-06-02 14:26
So, seems that the fix for VHS 94 wasn't that hard as the season isn't tagged like that (with a dot between s and number). I'm gonna run a few tests but should be good for the next release.

As for HULU: This behaviour was intended as I expect this to be a show made by HULU. I'm gonna fix it as they also stream movies. This behaviour is only seen in p2p release name, scene release groups always tag with just "WEB" as source.

**Comment by pr0pz** [comment] 2024-06-02 16:26
Fixed with newest release:

https://github.com/pr0pz/scene-release-parser-php/releases/tag/v1.5.0

**Closed by pr0pz** 2024-06-02 16:26 UTC
